import { Doctor } from "@/models/doctors";

export const DOCTORS_LIST: Doctor[] = [
  {
    id: "1",
    name: "Dr. Rahul Deshmukh",
    specialty: "Pediatrics",
    rating: "4.9",
    reviews: 123,
    price: "₹850",
    exp: "+10 year",
    patients: "+617",
    location: "Ruby Hall Clinic, Pune",
    image: "https://randomuser.me/api/portraits/men/42.jpg?nat=in",
  },
  {
    id: "2",
    name: "Dr. Priya Sharma",
    specialty: "Nephrologist",
    rating: "4.6",
    reviews: 317,
    price: "₹900",
    exp: "+8 year",
    patients: "+423",
    location: "Jehangir Hospital, Pune",
    image: "https://randomuser.me/api/portraits/women/62.jpg?nat=in",
  },
  {
    id: "3",
    name: "Dr. Amit Kulkarni",
    specialty: "Dentist",
    rating: "4.9",
    reviews: 85,
    price: "₹500",
    exp: "+5 year",
    patients: "+200",
    location: "Baner Dental Care, Pune",
    image: "https://randomuser.me/api/portraits/men/31.jpg?nat=in",
  },
  {
    id: "4",
    name: "Dr. Sneha Joshi",
    specialty: "Urologist",
    rating: "4.8",
    reviews: 168,
    price: "₹1200",
    exp: "+12 year",
    patients: "+890",
    location: "Manipal Hospital, Kharadi",
    image: "https://randomuser.me/api/portraits/women/43.jpg?nat=in",
  },
  {
    id: "5",
    name: "Dr. Anjali Patil",
    specialty: "Cardiologist",
    rating: "4.8",
    reviews: 220,
    price: "₹1500",
    exp: "+15 year",
    patients: "+1k",
    location: "Deenanath Mangeshkar Hospital",
    image: "https://randomuser.me/api/portraits/women/24.jpg?nat=in",
  },
];
