import { Doctor } from "@/models/doctors";

export const DOCTORS_LIST: Doctor[] = [
  {
    id: "1",
    name: "Dr. Rahul Deshmukh",
    specialty: "Pediatrics",
    rating: "4.9",
    reviews: 123,
    price: "₹850",
    exp: "+10 year",
    patients: "+617",
    location: "Ruby Hall Clinic, Pune",
    image: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    id: "2",
    name: "Dr. Priya Sharma",
    specialty: "Nephrologist",
    rating: "4.6",
    reviews: 317,
    price: "₹900",
    exp: "+8 year",
    patients: "+423",
    location: "Jehangir Hospital, Pune",
    image: "https://randomuser.me/api/portraits/women/42.jpg",
  },
  {
    id: "3",
    name: "Dr. Amit Kulkarni",
    specialty: "Dentist",
    rating: "4.9",
    reviews: 85,
    price: "₹500",
    exp: "+5 year",
    patients: "+200",
    location: "Baner Dental Care, Pune",
    image: "https://randomuser.me/api/portraits/men/43.jpg",
  },
  {
    id: "4",
    name: "Dr. Sneha Joshi",
    specialty: "Ophthalmologist",
    rating: "4.8",
    reviews: 168,
    price: "₹1200",
    exp: "+12 year",
    patients: "+890",
    location: "Sanjivan Eye Hospital, Kharadi",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: "5",
    name: "Dr. Anjali Patil",
    specialty: "Cardiologist",
    rating: "4.8",
    reviews: 220,
    price: "₹1500",
    exp: "+15 year",
    patients: "+1k",
    location: "Deenanath Mangeshkar Hospital",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    id: "6",
    name: "Dr. Vikram Singh",
    specialty: "Dentist",
    rating: "4.7",
    reviews: 142,
    price: "₹600",
    exp: "+7 year",
    patients: "+350",
    location: "Smiles Dental Clinic, Viman Nagar",
    image: "https://randomuser.me/api/portraits/men/46.jpg",
  },
  // --- NEW DOCTORS BELOW ---
  {
    id: "7",
    name: "Dr. Siddharth Joshi",
    specialty: "Orthopedist",
    rating: "4.8",
    reviews: 195,
    price: "₹1000",
    exp: "+14 year",
    patients: "+800",
    location: "Sancheti Hospital, Shivajinagar",
    image: "https://randomuser.me/api/portraits/men/47.jpg",
  },
  {
    id: "8",
    name: "Dr. Meera Reddy",
    specialty: "Dermatologist",
    rating: "4.7",
    reviews: 250,
    price: "₹800",
    exp: "+9 year",
    patients: "+550",
    location: "SkinCare Clinic, Koregaon Park",
    image: "https://randomuser.me/api/portraits/women/48.jpg",
  },
  {
    id: "9",
    name: "Dr. Rohan Mehta",
    specialty: "General Physician",
    rating: "4.9",
    reviews: 410,
    price: "₹500",
    exp: "+12 year",
    patients: "+2k",
    location: "Apollo Clinic, Aundh",
    image: "https://randomuser.me/api/portraits/men/49.jpg",
  },
  {
    id: "10",
    name: "Dr. Kavita Nair",
    specialty: "Gynecologist",
    rating: "4.9",
    reviews: 320,
    price: "₹1100",
    exp: "+16 year",
    patients: "+1.5k",
    location: "Cloudnine Hospital, Kalyani Nagar",
    image: "https://randomuser.me/api/portraits/women/50.jpg",
  },
];
